import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';

/**
 * Generate a PDF document buffer for an application submission
 */
export async function generateApplicationPdf({
  submissionId,
  receiptCode,
  formTitle,
  categoryTitle,
  fieldValues, // Array of { label, value, confirmedAt }
  submittedAt
}) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Generate QR Code as DataURL
      const qrDataUrl = await QRCode.toDataURL(
        `https://bolvaani.gov.in/verify/${receiptCode}?sub=${submissionId}`,
        { width: 140, margin: 1 }
      );
      const qrBuffer = Buffer.from(qrDataUrl.replace(/^data:image\/png;base64,/, ''), 'base64');

      // Header Banner
      doc.rect(40, 40, 515, 75).fill('#065f46'); // Deep emerald

      doc.fillColor('#ffffff')
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('BOLVAANI OFFICIAL APPLICATION RECEIPT', 55, 55);

      doc.fontSize(12)
        .font('Helvetica')
        .text('National Voice-First Assistive Portal for Public Services & Welfare', 55, 82);

      // Receipt Reference Code Box
      doc.rect(40, 130, 340, 95).fill('#ecfdf5').stroke('#059669');

      doc.fillColor('#065f46')
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('SPOKEN REFERENCE CODE / APPLICATION NUMBER', 55, 145);

      doc.fillColor('#047857')
        .fontSize(32)
        .font('Helvetica-Bold')
        .text(receiptCode, 55, 162);

      doc.fontSize(9)
        .font('Helvetica')
        .fillColor('#374151')
        .text(`Submitted On: ${new Date(submittedAt).toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`, 55, 202);

      // QR Code Placement
      doc.image(qrBuffer, 415, 120, { width: 100, height: 100 });
      doc.fontSize(8)
        .fillColor('#4b5563')
        .text('Scan to Verify Online', 420, 222, { align: 'center', width: 90 });

      // Scheme / Job Details
      doc.rect(40, 245, 515, 30).fill('#f3f4f6');
      doc.fillColor('#111827')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(`Category: ${categoryTitle}  |  Scheme: ${formTitle}`, 55, 255);

      // Fields Section
      let currentY = 295;
      doc.fillColor('#111827')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Recorded & Confirmed Spoken Information:', 40, currentY);

      currentY += 25;

      fieldValues.forEach((fv, index) => {
        // Alternating row background
        if (index % 2 === 0) {
          doc.rect(40, currentY - 5, 515, 34).fill('#f9fafb');
        }

        doc.fillColor('#4b5563')
          .fontSize(10)
          .font('Helvetica-Bold')
          .text(fv.label, 50, currentY);

        doc.fillColor('#111827')
          .fontSize(11)
          .font('Helvetica')
          .text(fv.value || 'Not provided', 230, currentY);

        doc.fillColor('#059669')
          .fontSize(9)
          .font('Helvetica-Bold')
          .text('✓ Voice Confirmed', 440, currentY);

        currentY += 34;
      });

      // Voice Signature Verification Stamp
      currentY += 25;
      doc.rect(40, currentY, 515, 65).fill('#eff6ff').stroke('#3b82f6');

      doc.fillColor('#1e40af')
        .fontSize(11)
        .font('Helvetica-Bold')
        .text('VOICE SIGNATURE AUDIT TIMESTAMP', 55, currentY + 12);

      doc.fillColor('#1f2937')
        .fontSize(9)
        .font('Helvetica')
        .text('The applicant reviewed this application via voice read-back and provided spoken consent.', 55, currentY + 28);

      doc.fillColor('#4b5563')
        .fontSize(8)
        .text(`Submission ID: ${submissionId}  |  Authenticity Hash: ${Buffer.from(submissionId).toString('base64').slice(0, 16)}`, 55, currentY + 44);

      // Footer
      doc.fontSize(8)
        .fillColor('#9ca3af')
        .text('Generated by BolVaani Assistive AI Engine. No signature or typing was required by the applicant.', 40, 770, { align: 'center', width: 515 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
